// Government services catalog.
// TODO: Replace with data fetched from Supabase `services` table when Cloud is enabled.

export type Service = {
  id: string;
  name: string;
  category: string;
  icon: string; // lucide icon name
  description: string;
  eligibility: string[];
  documents: string[];
  processingTime: string;
  fees: string;
  steps: string[];
  officialUrl: string;
  faqs: { q: string; a: string }[];
  related: string[];
};

export const SERVICES: Service[] = [
  {
    id: "aadhaar",
    name: "Aadhaar Card",
    category: "Identity",
    icon: "IdCard",
    description: "12-digit unique identity number issued by UIDAI to residents of India.",
    eligibility: ["Resident of India", "Any age (including newborns)"],
    documents: ["Proof of Identity", "Proof of Address", "Proof of Date of Birth"],
    processingTime: "10–15 working days",
    fees: "Free for first enrolment; ₹50 for updates",
    steps: [
      "Locate nearest Aadhaar Seva Kendra",
      "Book an appointment online",
      "Visit centre with original documents",
      "Complete biometric capture",
      "Track status using enrolment ID",
    ],
    officialUrl: "https://uidai.gov.in",
    faqs: [
      { q: "Is Aadhaar mandatory?", a: "It is required for most government subsidies and services." },
      { q: "Can I update my address online?", a: "Yes, via the mAadhaar app or UIDAI portal." },
    ],
    related: ["pan", "voter-id", "ration-card"],
  },
  {
    id: "pan",
    name: "PAN Card",
    category: "Identity",
    icon: "CreditCard",
    description: "Permanent Account Number issued by the Income Tax Department.",
    eligibility: ["Indian citizen or entity earning taxable income"],
    documents: ["Aadhaar", "Proof of Date of Birth", "Passport-size photo"],
    processingTime: "7–15 working days",
    fees: "₹110 (India) / ₹1,020 (abroad)",
    steps: ["Fill Form 49A online", "Upload documents", "Pay fee", "e-KYC via Aadhaar OTP", "Receive PAN"],
    officialUrl: "https://www.onlineservices.nsdl.com",
    faqs: [{ q: "Can I hold two PANs?", a: "No, holding two PANs is illegal." }],
    related: ["aadhaar"],
  },
  {
    id: "passport",
    name: "Passport",
    category: "Travel",
    icon: "BookMarked",
    description: "Official travel document issued by the Ministry of External Affairs.",
    eligibility: ["Indian citizen"],
    documents: ["Aadhaar", "PAN", "Proof of Address", "Birth Certificate"],
    processingTime: "30–45 days (Normal), 7–14 days (Tatkaal)",
    fees: "₹1,500 – ₹3,500",
    steps: [
      "Register on Passport Seva Portal",
      "Fill application form",
      "Book appointment at PSK",
      "Attend appointment with originals",
      "Police verification",
      "Passport dispatch",
    ],
    officialUrl: "https://www.passportindia.gov.in",
    faqs: [{ q: "What is Tatkaal?", a: "A faster processing option at higher fees." }],
    related: ["aadhaar", "pan"],
  },
  {
    id: "driving-licence",
    name: "Driving Licence",
    category: "Transport",
    icon: "Car",
    description: "Official licence to drive a motor vehicle in India.",
    eligibility: ["18+ for LMV", "16+ for gearless two-wheeler (≤50cc)"],
    documents: ["Aadhaar", "Age Proof", "Address Proof", "Learner's Licence"],
    processingTime: "30 days",
    fees: "₹200 – ₹1,000",
    steps: ["Apply for Learner's Licence", "Pass online test", "Practice for 30 days", "Book slot for driving test", "Receive DL"],
    officialUrl: "https://parivahan.gov.in",
    faqs: [{ q: "Validity?", a: "20 years or until age 40, whichever earlier." }],
    related: ["aadhaar"],
  },
  {
    id: "birth-certificate",
    name: "Birth Certificate",
    category: "Civil",
    icon: "Baby",
    description: "Official record of a person's birth issued by municipal authorities.",
    eligibility: ["Any Indian resident"],
    documents: ["Hospital birth record", "Parents' ID proof", "Address proof"],
    processingTime: "7–21 days",
    fees: "₹20 – ₹100",
    steps: ["Apply within 21 days at municipal office", "Submit documents", "Verification", "Collect certificate"],
    officialUrl: "https://crsorgi.gov.in",
    faqs: [],
    related: ["aadhaar"],
  },
  {
    id: "death-certificate",
    name: "Death Certificate",
    category: "Civil",
    icon: "FileText",
    description: "Legal record of a person's death.",
    eligibility: ["Family member or authorised person"],
    documents: ["Medical certificate", "ID of deceased", "Applicant ID"],
    processingTime: "7–14 days",
    fees: "₹20 – ₹100",
    steps: ["Register within 21 days", "Submit medical certificate", "Verification", "Collect certificate"],
    officialUrl: "https://crsorgi.gov.in",
    faqs: [],
    related: [],
  },
  {
    id: "income-certificate",
    name: "Income Certificate",
    category: "Certificates",
    icon: "IndianRupee",
    description: "Certifies the annual income of a family, issued by the Revenue Department.",
    eligibility: ["Indian resident"],
    documents: ["Aadhaar", "Ration Card", "Salary Slip / ITR", "Address Proof"],
    processingTime: "15–30 days",
    fees: "₹10 – ₹50",
    steps: ["Apply online via MeeSeva / e-District", "Upload documents", "Tehsildar verification", "Download certificate"],
    officialUrl: "https://services.india.gov.in",
    faqs: [{ q: "Validity?", a: "Typically valid for 1 year." }],
    related: ["caste-certificate", "scholarships", "ration-card"],
  },
  {
    id: "caste-certificate",
    name: "Caste Certificate",
    category: "Certificates",
    icon: "Users",
    description: "Certifies that a person belongs to SC/ST/OBC as per government records.",
    eligibility: ["Belonging to reserved category as per Constitution of India"],
    documents: ["Aadhaar", "Ration Card", "Father's caste certificate", "Address proof"],
    processingTime: "15–30 days",
    fees: "₹10 – ₹50",
    steps: [
      "Apply through MeeSeva / e-District portal",
      "Attach supporting documents",
      "Field verification by VRO/Revenue Inspector",
      "Approval by Tehsildar",
      "Download digital certificate",
    ],
    officialUrl: "https://services.india.gov.in",
    faqs: [
      { q: "Is it valid across states?", a: "Yes, but re-verification may be required in some states." },
      { q: "How long does it take?", a: "Typically 15 to 30 days depending on state." },
    ],
    related: ["income-certificate", "residence-certificate", "scholarships"],
  },
  {
    id: "residence-certificate",
    name: "Residence Certificate",
    category: "Certificates",
    icon: "Home",
    description: "Certifies permanent residence in a state or district.",
    eligibility: ["Resident of the concerned state for a required period"],
    documents: ["Aadhaar", "Ration Card", "Electricity bill", "School records"],
    processingTime: "15–30 days",
    fees: "₹10 – ₹50",
    steps: ["Apply via e-District", "Upload proofs", "Verification", "Download certificate"],
    officialUrl: "https://services.india.gov.in",
    faqs: [],
    related: ["caste-certificate", "income-certificate"],
  },
  {
    id: "marriage-certificate",
    name: "Marriage Certificate",
    category: "Civil",
    icon: "Heart",
    description: "Legal proof of marriage under Hindu Marriage Act / Special Marriage Act.",
    eligibility: ["Legally married couple"],
    documents: ["Aadhaar of both spouses", "Wedding invitation", "Witnesses' ID", "Photographs"],
    processingTime: "15–60 days",
    fees: "₹100 – ₹500",
    steps: ["Apply at Registrar's office", "Submit documents", "Notice period (if applicable)", "Registration"],
    officialUrl: "https://services.india.gov.in",
    faqs: [],
    related: ["aadhaar"],
  },
  {
    id: "ration-card",
    name: "Ration Card",
    category: "Welfare",
    icon: "ShoppingBasket",
    description: "Entitles a family to subsidised food grains under the PDS.",
    eligibility: ["Indian citizen without an existing ration card"],
    documents: ["Aadhaar of all members", "Address proof", "Income certificate", "Family photo"],
    processingTime: "30–45 days",
    fees: "₹5 – ₹50",
    steps: ["Apply at PDS office", "Field verification", "Card issuance"],
    officialUrl: "https://nfsa.gov.in",
    faqs: [],
    related: ["aadhaar", "income-certificate"],
  },
  {
    id: "voter-id",
    name: "Voter ID (EPIC)",
    category: "Identity",
    icon: "Vote",
    description: "Electoral Photo Identity Card issued by the Election Commission.",
    eligibility: ["Indian citizen aged 18+"],
    documents: ["Aadhaar", "Age proof", "Address proof", "Passport photo"],
    processingTime: "15–30 days",
    fees: "Free",
    steps: ["Fill Form 6 on NVSP", "Upload documents", "BLO verification", "Card dispatch"],
    officialUrl: "https://www.nvsp.in",
    faqs: [],
    related: ["aadhaar"],
  },
  {
    id: "pension",
    name: "Pension Schemes",
    category: "Welfare",
    icon: "HandCoins",
    description: "Social security pension schemes for senior citizens, widows and differently-abled.",
    eligibility: ["Depends on scheme (age, income, category)"],
    documents: ["Aadhaar", "Age proof", "Bank passbook", "Income certificate"],
    processingTime: "30–60 days",
    fees: "Free",
    steps: ["Identify scheme", "Apply at Mandal office / online portal", "Verification", "Monthly disbursement"],
    officialUrl: "https://nsap.nic.in",
    faqs: [],
    related: ["aadhaar", "income-certificate"],
  },
  {
    id: "scholarships",
    name: "Scholarships",
    category: "Education",
    icon: "GraduationCap",
    description: "Central and state scholarships for students from various categories.",
    eligibility: ["Students meeting scheme criteria"],
    documents: ["Aadhaar", "Income certificate", "Caste certificate", "Bank passbook", "Marks card"],
    processingTime: "60–120 days",
    fees: "Free",
    steps: ["Register on NSP", "Fill application", "Institute verification", "State verification", "Disbursement"],
    officialUrl: "https://scholarships.gov.in",
    faqs: [],
    related: ["income-certificate", "caste-certificate", "aadhaar"],
  },
  {
    id: "health-schemes",
    name: "Health Schemes (Ayushman)",
    category: "Health",
    icon: "HeartPulse",
    description: "Ayushman Bharat PM-JAY provides ₹5 lakh health coverage per family per year.",
    eligibility: ["Families listed in SECC 2011 database"],
    documents: ["Aadhaar", "Ration card", "Mobile number"],
    processingTime: "Instant card generation at CSC",
    fees: "Free",
    steps: ["Check eligibility on PM-JAY portal", "Visit CSC / hospital", "Generate Ayushman card"],
    officialUrl: "https://pmjay.gov.in",
    faqs: [],
    related: ["aadhaar", "ration-card"],
  },
];

export const CATEGORIES = Array.from(new Set(SERVICES.map((s) => s.category)));

export function getService(id: string): Service | undefined {
  return SERVICES.find((s) => s.id === id);
}
